In [15]:
import sklearn.datasets as sl
from sklearn.model_selection import train_test_split
import numpy as np

house = sl.fetch_california_housing()
X = house.data
y = house.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
X_train, X_test, y_train, y_test

(array([[   3.2596    ,   33.        ,    5.0176565 , ...,    3.6918138 ,
           32.71      , -117.03      ],
        [   3.8125    ,   49.        ,    4.47354497, ...,    1.73809524,
           33.77      , -118.16      ],
        [   4.1563    ,    4.        ,    5.64583333, ...,    2.72321429,
           34.66      , -120.48      ],
        ...,
        [   2.9344    ,   36.        ,    3.98671727, ...,    3.33206831,
           34.03      , -118.38      ],
        [   5.7192    ,   15.        ,    6.39534884, ...,    3.17889088,
           37.58      , -121.96      ],
        [   2.5755    ,   52.        ,    3.40257649, ...,    2.10869565,
           37.77      , -122.42      ]], shape=(16512, 8)),
 array([[   1.6812    ,   25.        ,    4.19220056, ...,    3.87743733,
           36.06      , -119.01      ],
        [   2.5313    ,   30.        ,    5.03938356, ...,    2.67979452,
           35.14      , -119.46      ],
        [   3.4801    ,   52.        ,    3.97715472, ...,    1.36033229,
           37.8       , -122.44      ],
        ...,
        [   9.2298    ,   25.        ,    7.23767606, ...,    2.79049296,
           37.31      , -122.05      ],
        [   2.785     ,   36.        ,    5.28902954, ...,    2.58860759,
           36.77      , -119.76      ],
        [   3.5521    ,   17.        ,    3.98883929, ...,    3.72991071,
           34.22      , -118.37      ]], shape=(4128, 8)),
 array([1.03 , 3.821, 1.726, ..., 2.221, 2.835, 3.25 ], shape=(16512,)),
 array([0.477  , 0.458  , 5.00001, ..., 5.00001, 0.723  , 1.515  ],
       shape=(4128,)))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scale, y_train)
lr_train_score = lr.score(X_train_scale, y_train) 
lr_test_score = lr.score(X_test_scale, y_test)
print(f'lr_train_score: {lr_train_score} \nlr_test_score: {lr_test_score}')

train_score: 0.6125511913966952
test_score: 0.575787706032451

In [ ]:
import pandas as pd

lr_coef_df = pd.DataFrame({
    "feature": house.feature_names,
    "coefficient": lr.coef_
})
lr_coef_df.sort_values("coefficient",ascending=False)

      feature  coefficient
0      MedInc     0.854383
3   AveBedrms     0.339259
1    HouseAge     0.122546
4  Population    -0.002308
5    AveOccup    -0.040829
2    AveRooms    -0.294410
7   Longitude    -0.869842
6    Latitude    -0.896929

In [ ]:
from sklearn.linear_model import ElasticNet

en = ElasticNet(alpha=0.1, l1_ratio=0.5)
en.fit(X_train_scale, y_train)
en_train_score = en.score(X_train_scale, y_train) 
en_test_score = en.score(X_test_scale, y_test)
print(f'en_train_score: {en_train_score} \nen_test_score: {en_test_score}')
en_coef_df = pd.DataFrame({
    "feature": house.feature_names,
    "coefficient": en.coef_
})
en_coef_df.sort_values("coefficient",ascending=False)

en_train_score: 0.5307617190050342
en_test_score: 0.5147647043408882

      feature  coefficient
0      MedInc     0.713818
1    HouseAge     0.137288
2    AveRooms    -0.000000
3   AveBedrms     0.000000
4  Population     0.000000
5    AveOccup    -0.000000
7   Longitude    -0.133250
6    Latitude    -0.175737

In [44]:
coef_df = lr_coef_df.merge(
    en_coef_df,
    on="feature",
    how="inner",
    suffixes=("_Linear", "_ElasticNet")
)
coef_df["diffrence"] = coef_df.coefficient_Linear - coef_df.coefficient_ElasticNet
coef_df

      feature  coefficient_Linear  coefficient_ElasticNet  diffrence
0      MedInc            0.854383                0.713818   0.140565
1    HouseAge            0.122546                0.137288  -0.014742
2    AveRooms           -0.294410               -0.000000  -0.294410
3   AveBedrms            0.339259                0.000000   0.339259
4  Population           -0.002308                0.000000  -0.002308
5    AveOccup           -0.040829               -0.000000  -0.040829
6    Latitude           -0.896929               -0.175737  -0.721192
7   Longitude           -0.869842               -0.133250  -0.736592

In [47]:
from sklearn.decomposition import PCA

pca = PCA(5)
X_train_pca = pca.fit_transform(X_train_scale)
X_test_pca = pca.transform(X_test_scale)

lr_pca = LinearRegression()
lr_pca.fit(X_train_pca, y_train)
lr_pca_train_score = lr_pca.score(X_train_pca, y_train) 
lr_pca_test_score = lr_pca.score(X_test_pca, y_test)
print(f'lr_pca_train_score: {lr_pca_train_score} \nlr_pca_test_score: {lr_pca_test_score}')

lr_pca_train_score: 0.45672908210341046
lr_pca_test_score: 0.43292317070134145